- platform: mqtt
  unique_id: mqtt_gavin_phone_is_home_switch
  name: mqtt_gavin_phone_is_home_switch
  state_topic: "homeassistant/person_tracker/location/gavin"
  command_topic: "homeassistant/person_tracker/location/gavin"
  payload_on: "home"
  payload_off: "not_home"
  state_on: "home"
  state_off: "not_home"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  unique_id: mqtt_ceilidh_phone_is_home_switch
  name: mqtt_ceilidh_phone_is_home_switch
  state_topic: "homeassistant/person_tracker/location/ceilidh"
  command_topic: "homeassistant/person_tracker/location/ceilidh"
  payload_on: "home"
  payload_off: "not_home"
  state_on: "home"
  state_off: "not_home"
  optimistic: false
  qos: 0
  retain: true
