version: '2.4'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    mem_limit: 512mb
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
    healthcheck:
      test: [ "CMD", "echo", "-n", ">", "/dev/tcp/127.0.0.1/8083" ]
      interval: 15s
      timeout: 3s
      retries: 10
