apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: "1.1.2"
  interval: 8h0m0s
  install:
    remediation:
      retries: 3
  values:
    longhornManager:
      tolerations:
        - key: "prevent-longhorn"
          value: "true"
          operator: Exists
          effect: NoSchedule
    longhornDriver:
      tolerations:
        - key: "prevent-longhorn"
          value: "true"
          operator: Exists
          effect: NoSchedule
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
    ingress:
      enabled: true
      host: longhorn.prod.gsdev.me
