dist: focal
language: generic
before_install:
- sudo apt-get install software-properties-common -y
- sudo add-apt-repository ppa:wireguard/wireguard -y
- sudo apt-get -q update
- sudo apt-get install wireguard -y
- openssl aes-256-cbc -K $encrypted_92f9334872f5_key -iv $encrypted_92f9334872f5_iv -in ansible.enc -out .ansible -d
- openssl aes-256-cbc -K $encrypted_1b5f0921b339_key -iv $encrypted_1b5f0921b339_iv -in wg0.conf.enc -out wg0.conf -d
addons:
  apt:
    update: true
script:
  - sudo modprobe wireguard
  - sudo cp wg0.conf /etc/wireguard/wg0.conf
  - sudo systemctl start wg-quick@wg0.service
  - ping -c 4 172.16.16.100
