dist: focal
language: generic
before_install:
- sudo apt-get install wireguard
- curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
- openssl aes-256-cbc -K $encrypted_92f9334872f5_key -iv $encrypted_92f9334872f5_iv -in ansible.enc -out .ansible -d
- openssl aes-256-cbc -K $encrypted_1b5f0921b339_key -iv $encrypted_1b5f0921b339_iv -in wg0.conf.enc -out wg0.conf -d
- openssl aes-256-cbc -K $encrypted_3b1c0ad0367a_key -iv $encrypted_3b1c0ad0367a_iv -in ansible.password.enc -out ansible.password -d
- openssl aes-256-cbc -K $encrypted_ae48d87e6745_key -iv $encrypted_ae48d87e6745_iv -in kube_config.enc -out kube_config -d
addons:
  apt:
    update: true

before_script:
  # Get ready for Ansible & K8s
  - pip install ansible
  - export KUBECONFIG=$(pwd)/kube_config
  # Connect to the VPN
  - chmod 600 .ansible
  - sudo modprobe wireguard
  - sudo cp wg0.conf /etc/wireguard/wg0.conf

script:
  # Start & Test we are on the LAN
  - sudo systemctl start wg-quick@wg0.service
  - ping -c 4 172.16.16.100
  # Avoid ssh-key prompt
  - ssh-keyscan -H 172.16.16.8 >> ~/.ssh/known_hosts
  - ssh-keyscan -H 172.16.16.9 >> ~/.ssh/known_hosts

  # Go
  #- make ci
