dist: focal
language: generic
before_install:
- sudo apt-get install wireguard -y
- openssl aes-256-cbc -K $encrypted_92f9334872f5_key -iv $encrypted_92f9334872f5_iv -in ansible.enc -out .ansible -d
- openssl aes-256-cbc -K $encrypted_1b5f0921b339_key -iv $encrypted_1b5f0921b339_iv -in wg0.conf.enc -out wg0.conf -d
- openssl aes-256-cbc -K $encrypted_3b1c0ad0367a_key -iv $encrypted_3b1c0ad0367a_iv -in ansible.password.enc -out ansible.password -d
addons:
  apt:
    update: true
script:
  - chmod 600 .ansible
  - sudo modprobe wireguard
  - sudo cp wg0.conf /etc/wireguard/wg0.conf
  - sudo systemctl start wg-quick@wg0.service
  - ping -c 4 172.16.16.100
  - ssh-keyscan -H 172.16.16.5 >> ~/.ssh/known_hosts
  - ssh-keyscan -H 172.16.16.51 >> ~/.ssh/known_hosts
  - ssh-keyscan -H 172.16.16.52 >> ~/.ssh/known_hosts
  - ssh-keyscan -H 172.16.16.53 >> ~/.ssh/known_hosts
  - ssh -i .ansible root@172.16.16.5 "uptime"
  - cd ansible/
  - pip install ansible
  - ansible-playbook -i hosts.yml site.yml --private-key ../.ansible --vault-password-file ../ansible.password
