- name: install nfs & zeroconf packages
  package:
      name:
          - nfs-utils
          - avahi
          - avahi-autoipd
      state: latest
  notify:
      - enable nfs
      - restart nfs

- name: enable service avahi-daemon
  service:
      name: avahi-daemon
      enabled: true
      state: started

- name: Create directories for shares
  file:
      path: "{{nfs_dir}}/{{item}}"
      recurse: yes
      owner: nfsnobody
      group: nfsnobody
      mode: 0755
      state: directory
  with_items: "{{ nfs_folders }}"

- name: Copy exports file.
  template:
      src: exports.j2
      dest: /etc/exports
      owner: root
      group: root
      mode: 0644
  notify: reload nfs
