apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 45m0s
  dependsOn:
    - name: infrastructure
    - name: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/prod
  prune: true
  validation: client
