apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: glasgow-bin-collection-cron
spec:
  schedule: "0 7 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: glasgow-bin-collection
              image: gsdevme/glasgow-bin-collection-mqtt:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: glasgow-bin-config
          restartPolicy: OnFailure
