- name: restart nfs
  service:
      name: "{{ item }}"
      state: restarted
  with_items:
      - rpcbind
      - nfs-server
      - nfs-lock
      - nfs-idmap

- name: enable nfs
  service:
      name: "{{ item }}"
      enabled: true
  with_items:
      - rpcbind
      - nfs-server
      - nfs-lock
      - nfs-idmap

- name: reload nfs
  command: 'exportfs -ra'
