apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  type: ExternalName
  externalName: home-assistant.lan
  ports:
    - port: 80
      targetPort: 8123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: home-assistant.home.gsdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
  tls:
    - hosts:
        - home-assistant.home.gsdev.me
      secretName: home-assistant-home-gsdev-me-tls
