apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-ha-presence
data:
  TRACK_DEVICES: "Ceilidhs-Phone,iPhone-X"
  UNIFI_HOST: "https://172.16.16.1"
  MQTT_DNS: "mqtt://172.16.16.254:1883"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-ha-presence
  labels:
    app: unifi-ha-presence
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: unifi-ha-presence
  template:
    metadata:
      labels:
        app: unifi-ha-presence
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/arch"
                    operator: In
                    values: ["amd64"]
      containers:
        - name: unifi-ha-presence
          imagePullPolicy: IfNotPresent
          image: gsdevme/unifi-ha-presence-mqtt:v1.2.1
          envFrom:
            - configMapRef:
                name: unifi-ha-presence
            - secretRef:
                name: unifi-ha-presence
          resources:
            limits:
              memory: "32Mi"
              cpu: "50m"
