apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-lan
  namespace: local-lan-dns
  annotations:
    metallb.universe.tf/address-pool: lan-dns
spec:
  selector:
    app: dnsmasq-lan
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
  type: LoadBalancer
