apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-postgresql-pvc
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgresql-local-path
  resources:
    requests:
      storage: 25Gi
