apiVersion: v1
kind: ConfigMap
metadata:
  name: teslamate
data:
  MQTT_HOST: "mqtt.home.gsdev.me"
  DATABASE_NAME: "teslamate"
  DATABASE_USER: "postgres"
  DATABASE_HOST: "postgresql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslamate
  labels:
    app: teslamate
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: teslamate
  template:
    metadata:
      labels:
        app: teslamate
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/arch"
                    operator: In
                    values: ["arm64"]
      containers:
        - name: teslamate
          ports:
            - containerPort: 4000
          imagePullPolicy: IfNotPresent
          image: teslamate/teslamate:1.29.1
          envFrom:
            - configMapRef:
                name: teslamate
            - secretRef:
                name: teslamate
          resources:
            limits:
              memory: "1500Mi"
              cpu: "500m"
            requests:
              memory: "1500Mi"
              cpu: "500m"
