- platform: min_max
  type: mean
  name: 'Living Room Temperature'
  entity_ids:
    - sensor.mqtt_xiaomi_atc_34ef8f_living_room_temperature
    - sensor.mqtt_xiaomi_atc_15e359_living_room_temperature
