- platform: mqtt
  unique_id: "mqtt_xiaomi_atc_15e359_living_room_humidity"
  name: "mqtt_xiaomi_atc_15e359_living_room_humidity"
  state_topic: "esphome/tempcontroller/sensor/living_room_humidity/state"
  unit_of_measurement: '%'
  device_class: 'humidity'

- platform: mqtt
  unique_id: "mqtt_xiaomi_loft_room_humidity"
  name: "mqtt_xiaomi_loft_room_humidity"
  state_topic: "esphome/tempcontroller/sensor/loft_humidity/state"
  unit_of_measurement: '%'
  device_class: 'humidity'

- platform: mqtt
  unique_id: "mqtt_xiaomi_bathroom_humidity"
  name: "mqtt_xiaomi_bathroom_humidity"
  state_topic: "esphome/tempcontroller/sensor/bathroom_humidity/state"
  unit_of_measurement: '%'
  device_class: 'humidity'

- platform: mqtt
  unique_id: "mqtt_xiaomi_ensuite_humidity"
  name: "mqtt_xiaomi_ensuite_humidity"
  state_topic: "esphome/tempcontroller/sensor/ensuite_humidity/state"
  unit_of_measurement: '%'
  device_class: 'humidity'

- platform: mqtt
  unique_id: "mqtt_xiaomi_toilet_humidity"
  name: "mqtt_xiaomi_toilet_humidity"
  state_topic: "esphome/tempcontroller/sensor/toilet_humidity/state"
  unit_of_measurement: '%'
  device_class: 'humidity'

- platform: mqtt
  unique_id: "mqtt_xiaomi_office_humidity"
  name: "mqtt_xiaomi_office_humidity"
  state_topic: "esphome/tempcontroller/sensor/office_humidity/state"
  unit_of_measurement: '%'
  device_class: 'humidity'
