- platform: mqtt
  unique_id: "living_room_battery_level"
  name: "living_room_battery_level"
  state_topic: "esphome/tempcontroller/sensor/living_room_battery_level/state"
  unit_of_measurement: '%'
  device_class: 'battery'

- platform: mqtt
  unique_id: "living_room_2_battery_level"
  name: "living_room_2_battery_level"
  state_topic: "esphome/tempcontroller/sensor/living_room_2_battery_level/state"
  unit_of_measurement: '%'
  device_class: 'battery'

- platform: mqtt
  unique_id: "toilet_battery_level"
  name: "toilet_battery_level"
  state_topic: "esphome/tempcontroller/sensor/toilet_battery_level/state"
  unit_of_measurement: '%'
  device_class: 'battery'

- platform: mqtt
  unique_id: "master_bedroom_battery_level"
  name: "master_bedroom_battery_level"
  state_topic: "esphome/tempcontroller/sensor/master_bedroom_battery_level/state"
  unit_of_measurement: '%'
  device_class: 'battery'

- platform: mqtt
  unique_id: "ensuite_battery_level"
  name: "ensuite_battery_level"
  state_topic: "esphome/tempcontroller/sensor/ensuite_battery_level/state"
  unit_of_measurement: '%'
  device_class: 'battery'

- platform: mqtt
  unique_id: "hall_battery_level"
  name: "hall_battery_level"
  state_topic: "esphome/tempcontroller/sensor/hall_battery_level/state"
  unit_of_measurement: '%'
  device_class: 'battery'

- platform: mqtt
  unique_id: "loft_battery_level"
  name: "loft_battery_level"
  state_topic: "esphome/tempcontroller/sensor/loft_battery_level/state"
  unit_of_measurement: '%'
  device_class: 'battery'

- platform: mqtt
  unique_id: "bathroom_battery_level"
  name: "bathroom_battery_level"
  state_topic: "esphome/tempcontroller/sensor/bathroom_battery_level/state"
  unit_of_measurement: '%'
  device_class: 'battery'

- platform: mqtt
  unique_id: "office_battery_level"
  name: "office_battery_level"
  state_topic: "esphome/tempcontroller/sensor/office_battery_level/state"
  unit_of_measurement: '%'
  device_class: 'battery'
