- alias: 'Trigger alarm while armed away if motion'
  id: trigger_alarm_while_armed_away_if_motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_inside
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.automated_alarm_panel
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.automated_alarm_panel

- alias: 'RED ALERT'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.automated_alarm_panel
      to: "triggered"
  action:
    - service: notify.notify
      data:
        message: "ALARM! The alarm has been triggered"
    - service: light.turn_on
      entity_id:
        - light.living_room_playbar
        - light.living_room_light_strip
      data:
        brightness: 254
        transition: 1
        color_name: red
        effect: breathe


