- alias: 'Set blue bin date'
  trigger:
    platform: mqtt
    topic: 'gcc/bins/blue'
  condition: []
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.blue_bin
        date: '{{ trigger.payload_json.date }}'
- alias: 'Set brown bin date'
  trigger:
    platform: mqtt
    topic: 'gcc/bins/brown'
  condition: []
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.brown_bin
        date: '{{ trigger.payload_json.date }}'
- alias: 'Set green bin date'
  trigger:
    platform: mqtt
    topic: 'gcc/bins/green'
  condition: []
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.green_bin
        date: '{{ trigger.payload_json.date }}'
- alias: 'Set purple bin date'
  trigger:
    platform: mqtt
    topic: 'gcc/bins/purple'
  condition: []
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.purple_bin
        date: '{{ trigger.payload_json.date }}'
