- alias: 'Turn on hall/landing light when there is movement 4am-9pm'
  trigger:
    platform: state
    entity_id: binary_sensor.hall_or_landing_motion
    to: 'on'
  condition:
    - condition: time
      after: '04:00:00'
      before: '21:00:00'
    - condition: state
      entity_id: light.hall_lights
      state: 'off'
  action:
    service: light.turn_on
    target:
      entity_id: light.hall_lights
    data:
      brightness: 254
      transition: 1

- alias: 'Turn on hall/landing light when there is movement after 9pm but before 4am'
  trigger:
    platform: state
    entity_id: binary_sensor.hall_or_landing_motion
    to: 'on'
  condition:
    - condition: time
      before: '04:00:00'
      after: '21:00:00'
    - condition: state
      entity_id: light.hall_light
      state: 'off'
  action:
    service: light.turn_on
    target:
      # i.e. the downstairs one only (not the landing since they are near bedrooms)
      entity_id: light.hall_light
    data:
      brightness: 20

- alias: 'Turn off hall/landing light 3 minutes after last movement'
  trigger:
    platform: state
    entity_id: binary_sensor.hall_or_landing_motion
    to: 'off'
    for:
      minutes: 3
  action:
    service: light.turn_off
    target:
      entity_id: light.hall_lights
    data:
      transition: 10
