- alias: '[Kitchen] Turn on light when pressed on'
  trigger:
    platform: state
    entity_id: sensor.kitchen_switch_action
    to: 'on-press'
  condition:
    - condition: state
      entity_id: light.kitchen_lights
      state: 'off'
  action:
    - service: light.turn_on
      target:
        entity_id: light.kitchen_lights
      data:
        brightness: 254
        color_temp: 200
        transition: 1
    # Light strip cannot go over 200 as it will use more than 10 watts
    # @todo buy the 30 watt version once Covid-19 is over and you can visit IKEA
    - service: light.turn_on
      target:
        entity_id: light.kitchen_light_strip
      data:
        brightness: 190
        transition: 1

- alias: '[Kitchen] Turn off light when pressed off'
  trigger:
    platform: state
    entity_id: sensor.kitchen_switch_action
    to: 'off-press'
  action:
    - service: light.turn_off
      target:
        entity_id: light.kitchen_lights
    - service: light.turn_off
      target:
        entity_id: light.kitchen_light_strip

- alias: '[Kitchen] Turn on light when there is movement before 11pm'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
  condition:
    - condition: time
      before: '23:00:00'
    - condition: state
      entity_id: light.kitchen_lights
      state: 'off'
  action:
    - service: light.turn_on
      target:
        entity_id: light.kitchen_lights
      data:
        brightness: 254
        color_temp: 200
        transition: 1
    # Light strip cannot go over 200 as it will use more than 10 watts
    # @todo buy the 30 watt version once Covid-19 is over and you can visit IKEA
    - service: light.turn_on
      target:
        entity_id: light.kitchen_light_strip
      data:
        brightness: 190
        transition: 1

- alias: 'Turn on kitchen light when there is movement after 11pm'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
  condition:
    - condition: time
      after: '23:00:00'
    - condition: state
      entity_id: light.kitchen_lights
      state: 'off'
  action:
    - service: light.turn_on
      target:
        entity_id: light.kitchen_lights
      data:
        brightness: 60
    # Light strip cannot go over 200 as it will use more than 10 watts
    # @todo buy the 30 watt version once Covid-19 is over and you can visit IKEA
    - service: light.turn_on
      target:
        entity_id: light.kitchen_light_strip
      data:
        brightness: 190
        transition: 1

- alias: '[Kitchen] Start/Restart timer if occupancy OR light is switched on'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'on'
    - platform: state
      entity_id: light.kitchen_lights
      to: 'on'
      from: 'off'
  action:
    service: timer.start
    target:
      entity_id: timer.kitchen

- alias: "[Kitchen] If the timer ends but we still have occupancy reset it"
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen
  condition:
    - condition: state
      entity_id: binary_sensor.kitchen_motion
      state: 'on'
  action:
    service: timer.start
    target:
      entity_id: timer.kitchen

- alias: "[Kitchen] If the timer ends and we have no occupancy turn off the light"
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen
  condition:
    - condition: state
      entity_id: binary_sensor.kitchen_motion
      state: 'off'
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.kitchen_lights
        - light.kitchen_light_strip
