- alias: 'Turn on master bedroom light when pressed on'
  trigger:
    platform: state
    entity_id: sensor.master_bedroom_switch_action
    to: 'on-press'
  action:
    service: light.turn_on
    target:
      entity_id: light.master_bedroom_light
    data:
      brightness: 254

- alias: 'Turn off master bedroom light when pressed off'
  trigger:
    platform: state
    entity_id: sensor.master_bedroom_switch_action
    to: 'off-press'
  action:
    service: light.turn_off
    target:
      entity_id: light.master_bedroom_light
