apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-ha-presence
data:
  TRACK_DEVICES: "Ceilidhs-Phone,iPhone-X"
  UNIFI_HOST: "https://172.16.16.1"
  MQTT_DNS: "mqtt://mqtt.home.gsdev.me:1883"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-ha-presence
  labels:
    app: unifi-ha-presence
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: unifi-ha-presence
  template:
    metadata:
      labels:
        app: unifi-ha-presence
    spec:
      containers:
        - name: unifi-ha-presence
          imagePullPolicy: IfNotPresent
          image: gsdevme/unifi-ha-presence-mqtt:v1.0.1
          envFrom:
            - configMapRef:
                name: unifi-ha-presence
            - secretRef:
                name: unifi-ha-presence
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            limits:
              memory: "32Mi"
              cpu: "100m"
            requests:
              cpu: "50m"
