apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
spec:
  releaseName: influxdb2
  chart:
    spec:
      chart: influxdb2
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      version: "1.1.0"
  interval: 8h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: influxdb2-values
