apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 9.9.9.9
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - args:
            - start
          env:
            - name: vip_arp
              value: "true"
            - name: vip_interface
              value: ens18
            - name: vip_address
              value: 10.10.40.53
            - name: vip_leaderelection
              value: "true"
            - name: vip_leaseduration
              value: "5"
            - name: vip_renewdeadline
              value: "3"
            - name: vip_retryperiod
              value: "1"
          image: plndr/kube-vip:0.2.3
          imagePullPolicy: IfNotPresent
          name: kube-vip
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_TIME
          volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
            - mountPath: /etc/ssl/certs
              name: ca-certs
              readOnly: true
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        - hostPath:
            path: /etc/rancher/k3s/k3s.yaml
          name: kubeconfig
        - hostPath:
            path: /etc/ssl/certs
          name: ca-certs
  updateStrategy: {}
