apiVersion: apps/v1
kind: Deployment
metadata:
  name: ring-deployment
  labels:
    app: ring
spec:
  selector:
    matchLabels:
      app: ring
  template:
    metadata:
      labels:
        app: ring
    spec:
      containers:
        - name: ring
          # Terrible hack to just restart it every day (at 3am)
          livenessProbe:
            exec:
              command:
                - exit $(test $(date +%H) -eq 3 && echo 1 || echo 0)
            failureThreshold: 1
            initialDelaySeconds: 3600
            periodSeconds: 60
          imagePullPolicy: Always
          image: tsightler/ring-mqtt
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: ring-secrets
            - configMapRef:
                name: ring-config
