apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-nginx
  namespace: helloworld
  labels:
    app: mysite-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite-nginx
  template:
    metadata:
      labels:
        app: mysite-nginx
    spec:
      containers:
        - name: nginx
          image: gsdevme/tester_image:latest
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  namespace: helloworld
  name: svc-helloworld
spec:
  selector:
    app: mysite-nginx
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: helloworld
  name: mysite-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/whitelist-source-range: '172.16.16.1/24'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: "helloworld-config"
spec:
  rules:
    - host: phpinfo.home.gsdev.me
      http:
        paths:
          - backend:
              serviceName: svc-helloworld
              servicePort: 9000
  tls:
    - hosts:
        - phpinfo.home.gsdev.me
      secretName: phpinfo-home-gsdev-me-tls
