apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "3.34.0"
  interval: 0h30m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      service:
        type: LoadBalancer
        externalTrafficPolicy: local
      config:
        use-gzip: true
        gzip-level: 9
        use-forwarded-headers: true

