- alias: 'Set gavin not_home when not home'
  trigger:
    - platform: zone
      event: leave
      zone: zone.home
      entity_id: device_tracker.iphone_x
  action:
    - service: mqtt.publish
      data:
        topic: homeassistant/person_tracker/location/gavin
        payload: not_home
        retain: true
- alias: 'Set gavin home when home'
  trigger:
    - platform: zone
      event: enter
      zone: zone.home
      entity_id: device_tracker.iphone_x
  action:
    - service: mqtt.publish
      data:
        topic: homeassistant/person_tracker/location/gavin
        payload: home
        retain: true

- alias: 'Set blue bin date'
  trigger:
    platform: mqtt
    topic: "gcc/bins/blue"
  condition: []
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.blue_bin
        date: "{{ trigger.payload_json.date }}"
- alias: 'Set brown bin date'
  trigger:
    platform: mqtt
    topic: "gcc/bins/brown"
  condition: []
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.brown_bin
        date: "{{ trigger.payload_json.date }}"
- alias: 'Set green bin date'
  trigger:
    platform: mqtt
    topic: "gcc/bins/green"
  condition: []
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.green_bin
        date: "{{ trigger.payload_json.date }}"
- alias: 'Set purple bin date'
  trigger:
    platform: mqtt
    topic: "gcc/bins/purple"
  condition: []
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.purple_bin
        date: "{{ trigger.payload_json.date }}"
