homeassistant:
  name: Home
  unit_system: metric
  customize: !include customize.yaml
  latitude: !env_var LATITUDE 0.0
  longitude: !env_var LONGITUDE 0.0

http:
  use_x_forwarded_for: true
  login_attempts_threshold: 10
  ip_ban_enabled: true
  trusted_proxies:
    - 172.16.16.0/24
    - 10.0.0.0/8

api:

input_datetime:
  blue_bin:
    name: Blue Bin
    has_date: true
    has_time: false
  green_bin:
    name: Green Bin
    has_date: true
    has_time: false
  purple_bin:
    name: Purple Bin
    has_date: true
    has_time: false
  brown_bin:
    name: Brown Bin
    has_date: true
    has_time: false

camera:
  - platform: generic
    still_image_url: !env_var GARDEN_LEFT_CAMERA_SNAP 127.0.0.1
    stream_source: !env_var GARDEN_LEFT_CAMERA 127.0.0.1
    name: "Garden Left"

#image_processing:
#  - platform: doods
#    url: "http://172.16.16.136:8080"
#    detector: default
#    source:
#      - entity_id: camera.garden_left
#    file_out:
#      - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
#      - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
#    confidence: 50
#    scan_interval: 2
#    labels:
#      - name: person
#        confidence: 40

influxdb:
  api_version: 2
  ssl: false
  host: !env_var INFLUX_HOST 127.0.0.1
  token: !env_var INFLUX_TOKEN not_a_real_token
  bucket: home-assistant
  organization: be914a74245f8060
  tags:
    source: ha
  port: 80
  include:
    entities:
      - binary_sensor.is_gavin_asleep
      - binary_sensor.people_home
      - binary_sensor.mqtt_guest_mode
      - binary_sensor.all_lights_off
    domains:
      - alarm_control_panel
      - light
      - plant
      - person
      - timer
      - zone
    entity_globs:
      - binary_sensor.*_battery_*
      - binary_sensor.battery_*
      - sensor.*_steps
      - sensor.*_activity

alexa:
  smart_home:
    locale: en-GB
    filter:
      include_entities:
        - light.master_bedroom_light
        - light.all_lights
        - switch.mqtt_guest_mode_switch
        - vacuum.jeff
    entity_config:
      switch.mqtt_guest_mode_switch:
        name: "Guest Mode"
      vacuum.jeff:
        name: "Jeff"
      light.all_lights:
        name: "Everything"
      light.master_bedroom_light:
        name: "Master Bedroom Light"

logger:
  default: info
  logs:
    homeassistant.components.alexa: debug

mqtt:
  broker: !env_var MQTT_HOST 127.0.0.1
  discovery: true

recorder:
  purge_keep_days: 3
  include:
    domains:
      - sensor
      - switch
      - alarm_control_panel
      - automation
      - person
      - vacuum
      - binary_sensor
      - plant
      - camera
      - sun
      - timer
  exclude:
    entity_globs:
      - '*illuminance'
      - '*motion_sensitivity'
      - '*update_available'
  db_url: !env_var RECORDER_DSN sqlite:////config/home-assistant.sqlite

weather:
frontend:

synology_dsm:
  - host: !env_var DSM_HOST 127.0.0.1
    username: !env_var DSM_USERNAME home-assistant
    password: !env_var DSM_PASSWORD home-assistant

mobile_app:
discovery:
ios:
map:
history:
sun:
logbook:
  exclude:
    entity_globs:
      - '*illuminance'
      - '*motion_sensitivity'
      - '*update_available'

zone:
  - name: Home
    latitude: !env_var LATITUDE 0.0
    longitude: !env_var LONGITUDE 0.0
    radius: 90
    icon: mdi:home

plant:
  kitchen_plant:
    sensors:
      moisture: sensor.mqtt_kitchen_plant_moisture
      conductivity: sensor.mqtt_kitchen_plant_conductivity
      temperature: sensor.mqtt_kitchen_plant_temperature
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 150
    max_conductivity: 600
    min_temperature: 10

sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary-sensors/
switch: !include_dir_merge_list switches/

neato:
  client_id: !env_var NEATO_CLIENT_ID ""
  client_secret: !env_var NEATO_CLIENT_SECRET ""

lovelace:
  mode: yaml
  resources:
    - url: /local/vacuum-card.js
      type: module
    - url: /local/auto-entities.js
      type: module
    - url: /local/layout-card.js
      type: module
    - url: /local/clockwork-card.js
      type: js

alarm_control_panel:
  - platform: template
    panels:
      #
      # 2. if someone is home dont set
      # 3. default set the alarm
      #
      automated_alarm_panel:
        code_arm_required: false
        value_template: >-
          {% if is_state('switch.mqtt_force_alarm_switch', 'on') %}
            armed_away
          {% elif is_state('binary_sensor.people_home', 'on') %}
            disarmed
          {% else %}
            armed_away
          {% endif %}

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

light:
  - platform: group
    name: hall_lights
    entities:
      - light.hall_light
      - light.landing_light
  - platform: group
    name: all_living_room_lights
    entities:
      - light.living_room_lamp
      - light.living_room_playbar
      - light.living_room_light
      - light.living_room_light_strip
  - platform: group
    name: living_room_lights
    entities:
      - light.living_room_lamp
      - light.living_room_playbar
      - light.living_room_light_strip
  - platform: group
    name: kitchen_lights
    entities:
      - light.kitchen_front_light
      - light.kitchen_rear_light
      - light.kitchen_light_strip
  - platform: group
    name: downstairs_lights
    entities:
      - light.hall_light
      - light.all_living_room_lights
      - light.living_room_lights
      - light.downstairs_cupboard_light
      - light.outside_light
      - light.kitchen_lights
  - platform: group
    name: upstairs_lights
    entities:
      - light.master_bedroom_light
      - light.office_light
      - light.landing_light
      - light.spare_bedroom_light
      - light.upstairs_cupboard
  - platform: group
    name: all_lights
    entities:
      - light.upstairs_lights
      - light.downstairs_lights

timer:
  kitchen:
    duration: "00:07:00"
  outside:
    duration: "00:02:00"
  office:
    duration: "00:05:00"

person:
  - name: Gavin
    id: gavin
    device_trackers:
      - device_tracker.iphone_x
      - device_tracker.iphone_x_2
    user_id: 101
  - name: Ceilidh
    id: ceilidh
    user_id: 102
    device_trackers:
      - device_tracker.ceilidhs_phone
