homeassistant:
  name: Home
  unit_system: metric
  customize: !include customize.yaml

mqtt:
  # TODO ADD DNS ENTRY AND USE ENV
  broker: !env_var MQTT_HOST

recorder:
  purge_keep_days: 3

frontend:

history:

sensor:
  !include_dir_merge_list sensors/

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

person:
  - name: Gavin
    id: gavin
    user_id: 101
