homeassistant:
  name: Home
  unit_system: metric
  customize: !include customize.yaml
  latitude: !env_var LATITUDE 0.0
  longitude: !env_var LONGITUDE 0.0

http:
  use_x_forwarded_for: true
  login_attempts_threshold: 10
  ip_ban_enabled: true
  trusted_proxies:
    - 172.16.16.0/24
    - 10.0.0.0/8

mqtt:
  broker: !env_var MQTT_HOST 127.0.0.1

recorder:
  purge_keep_days: 3

frontend:

synology_dsm:
  - host: !env_var DSM_HOST 127.0.0.1
    username: !env_var DSM_USERNAME home-assistant
    password: !env_var DSM_PASSWORD home-assistant

mobile_app:
discovery:
ios:
map:
history:
sun:

zone:
  - name: Home
    latitude: !env_var LATITUDE 0.0
    longitude: !env_var LONGITUDE 0.0
    radius: 90
    icon: mdi:home

plant:
  kitchen_plant:
    sensors:
      moisture: sensor.mqtt_kitchen_plant_moisture
      conductivity: sensor.mqtt_kitchen_plant_conductivity
      temperature: sensor.mqtt_kitchen_plant_temperature
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 150
    max_conductivity: 600
    min_temperature: 10

sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary-sensors/
switch: !include_dir_merge_list switches/

neato:
  username: !env_var NEATO_USERNAME ""
  password: !env_var NEATO_PASSWORD ""

lovelace:
  mode: yaml

alarm_control_panel:
  - platform: mqtt
    state_topic: "homeassistant/alarm/state"
    command_topic: "homeassistant/alarm/state"
    payload_disarm: "disarmed"
    payload_arm_away: "armed_away"
    payload_arm_home: "armed_home"
    payload_arm_night: "armed_night"
    retain: true

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

person:
  - name: Gavin
    id: gavin
    user_id: 101
  - name: Ceilidh
    id: ceilidh
    user_id: 102
