title: Home
views:
  - path: default_view
    title: Home
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        min_columns: 1
        max_columns: 3
        cards:
          - type: grid
            columns: 2
            cards:
              - type: vertical-stack
                cards:
                  - type: sensor
                    entity: sensor.living_room_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.kitchen_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.mqtt_xiaomi_a4_c1_38_a5_fd_de_bathroom_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.rest_rack_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.mqtt_xiaomi_atc_3ed9e6_master_bedroom_temperature
                    graph: line
                    hours_to_show: 6
              - type: vertical-stack
                cards:
                  - type: sensor
                    entity: sensor.mqtt_xiaomi_a4_c1_38_79_01_ce_ensuite_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.mqtt_xiaomi_toilet_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.mqtt_xiaomi_atc_58447f_office_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.hall_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.mqtt_xiaomi_loft_temperature
                    graph: line
                    hours_to_show: 6
          - break
          - type: glance
            entities:
              - entity: binary_sensor.mqtt_backdoor
              - entity: binary_sensor.mqtt_frontdoor
              - entity: binary_sensor.mqtt_office_window
            state_color: true
          - type: glance
            entities:
              - alarm_control_panel.automated_alarm_panel
              - switch.mqtt_guest_mode_switch
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              title: Batteries
            sort:
              numeric: true
            filter:
              include:
                - domain: sensor
                  attributes:
                    device_class: battery
              exclude:
                - state: unknown
                - state: '> 50'
          - type: custom:auto-entities
            show_empty: false
            card:
              type: glance
              state_color: true
            filter:
              include:
                - domain: person
          - type: custom:auto-entities
            card:
              type: entities
            filter:
              include:
                - entity_id: "*_humidity"
              exclude:
                - state: unknown
                - state: '< 60'
          - break
          - type: plant-status
            entity: plant.kitchen_plant
          - type: 'custom:vacuum-card'
            entity: vacuum.jeff
            compact_view: true
            stats:
              cleaning:
                - attribute: cleaned_area
                  unit: m2
                  subtitle: Cleaning area
                - attribute: cleaning_time
                  unit: minutes
                  subtitle: Cleaning time
          - type: vertical-stack
            title: Synology NAS
            cards:
              - type: horizontal-stack
                cards:
                  - type: gauge
                    entity: sensor.vault_cpu_load_5_min
                    min: 0
                    max: 400
                    severity:
                      green: 100
                      yellow: 275
                      red: 375
                  - type: gauge
                    entity: sensor.vault_volume_1_volume_used
                    min: 0
                    max: 100
                    severity:
                      green: 0
                      yellow: 85
                      red: 95
              - type: horizontal-stack
                cards:
                  - type: gauge
                    entity: sensor.vault_temperature
                    min: 0
                    max: 100
                    severity:
                      green: 30
                      yellow: 45
                      red: 50
                  - type: gauge
                    entity: sensor.vault_volume_1_average_disk_temp
                    min: 0
                    max: 45
                    severity:
                      green: 30
                      yellow: 42
                      red: 48
  - path: debug
    title: Debug
    cards:
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - domain: switch
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: Batteries
        sort:
          numeric: true
        filter:
          include:
            - domain: sensor
              attributes:
                device_class: battery
