title: Home
views:
  - path: default_view
    title: Home
#    badges:
#      - entity: binary_sensor.mqtt_guest_mode
#      - entity: person.gavin
#      - entity: person.ceilidh
#      - entity: sensor.living_room_temperature
#      - entity: sensor.hall_temperature
#      - entity: sensor.kitchen_temperature
#      - entity: sensor.rest_rack_temperature
#      - entity: sensor.mqtt_xiaomi_a4_c1_38_a5_fd_de_bathroom_temperature
#      - entity: sensor.mqtt_xiaomi_a4_c1_38_79_01_ce_ensuite_temperature
    cards:
      - cards:
          - entity: sensor.living_room_temperature
            graph: line
            hours_to_show: 6
            theme: Backend-selected
            type: sensor
          - entity: sensor.kitchen_temperature
            graph: line
            hours_to_show: 6
            theme: Backend-selected
            type: sensor
          - entity: sensor.hall_temperature
            graph: line
            hours_to_show: 6
            theme: Backend-selected
            type: sensor
        type: horizontal-stack
      - cards:
          - entity: sensor.mqtt_xiaomi_a4_c1_38_a5_fd_de_bathroom_temperature
            graph: line
            hours_to_show: 6
            theme: Backend-selected
            type: sensor
          - entity: sensor.mqtt_xiaomi_a4_c1_38_79_01_ce_ensuite_temperature
            graph: line
            hours_to_show: 6
            theme: Backend-selected
            type: sensor
          - entity: sensor.rest_rack_temperature
            graph: line
            hours_to_show: 6
            theme: Backend-selected
            type: sensor
        type: horizontal-stack
      - cards:
          - entity: sensor.mqtt_xiaomi_atc_58447f_office_temperature
            graph: line
            hours_to_show: 6
            theme: Backend-selected
            type: sensor
          - entity: sensor.mqtt_xiaomi_atc_3ed9e6_master_bedroom_temperature
            graph: line
            hours_to_show: 6
            theme: Backend-selected
            type: sensor
          - entity: sensor.rest_rack_temperature
            graph: line
            hours_to_show: 6
            theme: Backend-selected
            type: sensor
        type: horizontal-stack
      - type: plant-status
        entity: plant.kitchen_plant
      - type: entities
        entities:
          - switch.mqtt_guest_mode_switch
        title: Switch
