- platform: rest
  resource: http://172.16.16.75/api/ONBr4rlbegM2PSwlJ1suZi9HnH4aka9dX9OmvJDa/sensors/17
  value_template: '{{ value_json.state.presence }}'
  device_class: motion
  name: 'Kitchen_motion_sensor'
  scan_interval: 10

- platform: rest
  resource: http://172.16.16.75/api/ONBr4rlbegM2PSwlJ1suZi9HnH4aka9dX9OmvJDa/sensors/11
  value_template: '{{ value_json.state.presence }}'
  device_class: motion
  name: 'landing_motion_sensor'
  scan_interval: 10

- platform: rest
  resource: http://172.16.16.75/api/ONBr4rlbegM2PSwlJ1suZi9HnH4aka9dX9OmvJDa/sensors/29
  value_template: '{{ value_json.state.presence }}'
  device_class: motion
  name: 'frontdoor_motion_sensor'
  scan_interval: 10

#- platform: rest
#  resource: http://172.16.16.75/api/ONBr4rlbegM2PSwlJ1suZi9HnH4aka9dX9OmvJDa/sensors/44
#  value_template: '{{ value_json.state.presence }}'
#  device_class: motion
#  name: 'living_room_sensor'
#  scan_interval: 10

- platform: rest
  resource: http://172.16.16.75/api/ONBr4rlbegM2PSwlJ1suZi9HnH4aka9dX9OmvJDa/sensors/49
  value_template: '{{ value_json.state.presence }}'
  device_class: motion
  name: 'kitchen_rear_motion_sensor'
  scan_interval: 10
