- platform: mqtt
  name: "mqtt_frontdoor"
  state_topic: "tele/sonoff/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "2D3A0A"
  payload_off: "2D3A0E"
  device_class: Door
  qos: 1
