- platform: mqtt
  name: "mqtt_frontdoor"
  state_topic: "tele/sonoff/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "2D3A0A"
  payload_off: "2D3A0E"
  device_class: Door
  qos: 1
- platform: mqtt
  name: "mqtt_backdoor"
  state_topic: "tele/sonoff/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "2CDA0A"
  payload_off: "2CDA0E"
  device_class: Door
  qos: 1
- platform: mqtt
  name: "mqtt_office_window"
  state_topic: "tele/sonoff/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "2D780A"
  payload_off: "2D780E"
  device_class: window
  qos: 1
