- platform: template
  sensors:
    people_home:
      value_template: >-
        {{ is_state('person.gavin', 'home')
           or is_state('person.gavin', 'unknown')
           or is_state('person.ceilidh', 'home')
           or is_state('person.ceilidh', 'unknown')
           or is_state('binary_sensor.mqtt_guest_mode', 'on') }}
    phone_is_charging:
      value_template: >-
        {{ is_state('sensor.iphone_x_battery_state', 'Charging') }}
    all_lights_off:
      value_template: >-
        {{ states['light'] | count == states['light'] | selectattr('off','eq', state) | list | count }}
    is_gavin_asleep:
      value_template: >-
        {{ now().hour > 20
          and now().hour < 9
          and is_state('all_lights_off', 'on') }}
          and is_state('person.gavin', 'home')
          and is_state('sensor.phone_is_charging', 'on') }}
