- platform: template
  sensors:
    people_home:
      value_template: >-
        {{ is_state('device_tracker.gavin_phone_via_mqtt', 'home')
           or is_state('device_tracker.ceilidh_phone_via_mqtt', 'home')
           or is_state('binary_sensor.mqtt_guest_mode', 'on') }}
#- platform: template
#  sensors:
#    motion_at_home:
#      value_template: >-
#        {{ is_state('device_tracker.gavin_phone', 'home')
#           or is_state('device_tracker.ceilidh_phone', 'home')
#           or is_state('binary_sensor.mqtt_guest_mode', 'on') }}
