- platform: template
  sensors:
    people_home:
      value_template: >-
        {{ is_state('person.gavin', 'home')
           or is_state('person.gavin', 'unknown')
           or is_state('person.ceilidh', 'home')
           or is_state('person.ceilidh', 'unknown')
           or is_state('binary_sensor.mqtt_guest_mode', 'on') }}
    phone_is_charging:
      value_template: >-
        {{ is_state('sensor.iphone_x_battery_state', 'Charging') }}
    all_lights_off:
      value_template: >
        {{ is_state('light.all_lights', 'off') }}
    is_gavin_asleep:
      value_template: >-
        {{ now().hour > 20
          and now().hour < 9
          and is_state('all_lights_off', 'on')
          and is_state('person.gavin', 'home')
          and is_state('sensor.phone_is_charging', 'on') }}
    hall_or_landing_motion:
      value_template: >-
        {{ is_state('binary_sensor.landing_sensor_bookcase_occupancy', 'on')
          or is_state('binary_sensor.landing_sensor_occupancy', 'on')
          or is_state('binary_sensor.hall_sensor_occupancy', 'on') }}
    kitchen_motion:
      value_template: >-
        {{ is_state('binary_sensor.kitchen_front_sensor_occupancy', 'on')
          or is_state('binary_sensor.kitchen_rear_sensor_occupancy', 'on') }}


