alertmanager:
  enabled: false

#grafana:
#  enabled: false

kubeEtcd:
  enabled: false

prometheus:
  enabled: true
  serviceAccount:
    create: true
  thanosService:
    enabled: true
  servicePerReplica:
    enabled: false
  thanosIngress:
    enabled: false
  ingress:
    enabled: false
  ingressPerReplica:
    enabled: false
  serviceMonitor:
    selfMonitor: true
  prometheusSpec:
    retention: 3d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi
