esphome:
  name: tempcontroller
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

mqtt:
  broker: mqtt.home.gsdev.me
  discovery: false
  topic_prefix: 'esphome/tempcontroller'

logger:
  level: INFO
#  level: DEBUG

ota:

#web_server:
#  port: 80
#  auth:
#    username: admin
#    password: !secret web_server_password

esp32_ble_tracker:

#text_sensor:
#  - platform: ble_scanner
#    name: "BLE Devices Scanner"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 180s
  - platform: uptime
    name: "Uptime Sensor"
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:64:B9'
    temperature:
      name: "Kitchen Plant Temperature"
    moisture:
      name: "Kitchen Plant Moisture"
    illuminance:
      name: "Kitchen Plant Illuminance"
    conductivity:
      name: "Kitchen Plant Soil Conductivity"
    battery_level:
      name: "Kitchen Plant Battery Level"
  # ATC_15E359
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:15:E3:59"
    bindkey: "8f9e84d6f3b87fc00e0743b2ad819536" # NOT IMPORTANT, ITS BEEN FLASHED
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    battery_level:
      name: "Living Room Battery Level"
  # ATC_3ED9E6
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:3E:D9:E6"
    bindkey: "8f9e84d6f3b87fc00e0743b2ad819536" # NOT IMPORTANT, ITS BEEN FLASHED
    temperature:
      name: "Master Bedroom Temperature"
    humidity:
      name: "Master Bedroom Humidity"
    battery_level:
      name: "Master Bedroom Battery Level"
  # ATC_58447F
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:58:44:7F"
    bindkey: "8f9e84d6f3b87fc00e0743b2ad819536" # NOT IMPORTANT, ITS BEEN FLASHED
    temperature:
      name: "Toilet Temperature"
    humidity:
      name: "Toilet Humidity"
    battery_level:
      name: "Toilet Battery Level"
  # ATC_34EF8F
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:34:EF:8F"
    bindkey: "8f9e84d6f3b87fc00e0743b2ad819536" # NOT IMPORTANT, ITS BEEN FLASHED
    temperature:
      name: "Living Room 2 Temperature"
    humidity:
      name: "Living Room 2 Humidity"
    battery_level:
      name: "Living Room 2 Battery Level"
  # LYWSD03MMC
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:A5:FD:DE"
    bindkey: "098dba87c9955ea876df1dbaa7b12957"
    temperature:
      name: "Bathroom Temperature"
    humidity:
      name: "Bathroom Humidity"
    battery_level:
      name: "Bathroom Battery Level"
  # LYWSD03MMC
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:79:01:CE"
    bindkey: "a020d2053ffe80efcf01a22efbe9c3d0"
    temperature:
      name: "Ensuite Temperature"
    humidity:
      name: "Ensuite Humidity"
    battery_level:
      name: "Ensuite Battery Level"
  # MJ_HT_V1
  - platform: xiaomi_lywsdcgq
    mac_address: "58:2D:34:3B:91:0C"
    temperature:
      name: "Hall Temperature"
    humidity:
      name: "Hall Humidity"
    battery_level:
      name: "Hall Battery Level"
  # MJ_HT_V1
  - platform: xiaomi_lywsdcgq
    mac_address: "58:2D:34:3B:8E:16"
    temperature:
      name: "Office Temperature"
    humidity:
      name: "Office Humidity"
    battery_level:
      name: "Office Battery Level"
  # LYWSD03MMC
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:C4:84:F2"
    bindkey: "4551e1cdc36da979a549acd0f057955b"
    temperature:
      name: "Loft Temperature"
    humidity:
      name: "Loft Humidity"
    battery_level:
      name: "Loft Battery Level"
