apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-secret-generator
spec:
  releaseName: kubernetes-secret-generator
  chart:
    spec:
      chart: kubernetes-secret-generator
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
      version: "3.2.0"
  interval: 8h0m0s
  install:
    remediation:
      retries: 3
  values:
    secretLength: 16
