apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smokeping
resources:
  - ../../base/smokeping
  - basic-auth.yaml
  - ingress.yaml
patchesStrategicMerge:
  - statefulset.yaml
