apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq-lan
  labels:
    app: dnsmasq-lan
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dnsmasq-lan
  template:
    metadata:
      labels:
        app: dnsmasq-lan
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 9.9.9.9
          - 8.8.8.8
          - 8.8.4.4
      containers:
        - name: dnsmasq
          securityContext:
            privileged: true
            capabilities:
              add: [ "NET_ADMIN" ]
          image: gsdevme/lan_dns:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
